export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export CAP_VERSION="1.4.1"
export UAA_HELM_VERSION=" --version 2.17.1 "
export SCF_HELM_VERSION=" --version 2.17.1 "
export CONSOLE_HELM_VERSION=" --version 2.4.0 "
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export CFEP=https://api.cf.cap2jmlzone.com
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export CFEP=https://api.cf.cap2jmlzone.com
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
export KUBECONFIG=/home/jmlambert/capauto/CAP-080819/kubeconfig
